services:
  auth-api:
    image: auth-api
    build:
      context: ./auth-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME:-test-task}
      - SPRING_DATASOURCE_USERNAME=${DB_USER:-test-task}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-root}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - AUTHAPI_APP_SECRET=${SECRET:-r0jS0vlF0mdDvbR6sV9udF0odD7yz2asd0gs1g123guw3gn2r}
      - AUTHAPI_APP_LIFETIME=3600000
    ports:
      - "8080:8080"
  data-api:
    image: data-api
    build:
      context: ./data-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      - INTERLAL_TOKEN=${INTERNAL_TOKEN:-my-secret-token}
    ports:
      - "8081:8081"
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${DB_NAME:-test-task}"
      POSTGRES_USER: "${DB_USER:-test-task}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-root}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql

volumes:
  db-data: